### ISSUE TITLE
Adding a rough-time estimate of the last commit date for the Frameworks?

### ISSUE THREAD

**Issue by nyaahilism** [unixorn/awesome-zsh-plugins#1890]
I've already typed up the list, I just wanted to know if that was something that would be okay to add?

It's got dates by year, and anything that's had a commit in under the 1 year mark is just "recently" so it wouldn't need to much upkeep... I could even put in when the list was originally made so users could know how far off it was if I fail to update it within a timely schedule.

I just love going through your list so much and in terms of Frameworks, I feel like it would be helpful to know which ones are still actively maintained.

It's okay if you say no. I'll find another way to help you out someday~
lol `₍ᯫ᳐ >𖥦< ᯫ᳐₎`

Thanks for your time!

**Comment by unixorn** [comment]
Maybe add inline commit badges the same way I have them for the list in the status section.

For each framework, add a line with a badge for last commit and one for the star count on the line below the framework name.

Doing it with the badges would mean it gets updated automagically instead of needing manual intervention.

**Comment by unixorn** [comment]
The more I think about it the more I like this idea. I don't want to steal credit from you, so please file a PR otherwise I'll add it myself on Aug 31.

Thanks again for the suggestion.

**Comment by unixorn** [comment]
This was done in https://github.com/unixorn/awesome-zsh-plugins/pull/1911 and I forgot to close the issue.
